apiVersion: v2
name: nvidia-gpu-operator
description: NVIDIA GPU Operator for Kubernetes
version: 1.0.0
type: application

dependencies:
- name: gpu-operator
  version: "v25.10.1"
  repository: "https://helm.ngc.nvidia.com/nvidia"
